module.exports = {
	extends: "eslint:recommended",
	plugins: [
		"unicorn",
		"import",
	],
	rules: {
		"indent":                           ["error", "tab", { SwitchCase: 1 }],
		"linebreak-style":                  ["error", "unix"],
		"quotes":                           ["error", "double"],
		"semi":                             ["error", "never"],
		"no-unused-vars":                   ["error", { args: "none", varsIgnorePattern: "^_" }],
		"no-constructor-return":            ["error"],
		"no-duplicate-imports":             ["error"],
		"no-self-compare":                  ["error"],
		"no-template-curly-in-string":      ["error"],
		"no-unmodified-loop-condition":     ["error"],
		"no-unreachable-loop":              ["error"],
		"no-unused-private-class-members":  ["error"],
		"no-use-before-define":             ["error"],
		"require-atomic-updates":           ["error"],
		"accessor-pairs":                   ["error"],
		"no-var":                           ["error"],
		"camelcase":                        ["error", { properties: "always", ignoreDestructuring: true }],
		"class-methods-use-this":           ["error"],
		"complexity":                       ["error", { max: 20 }],
		"consistent-return":                ["error"],
		"curly":                            ["error", "multi-or-nest"],
		"default-case":                     ["error"],
		"default-case-last":                ["error"],
		"default-param-last":               ["error"],
		"dot-notation":                     ["error", { allowKeywords: true, allowPattern: "^[a-z]+(_[a-z]+)+$" }],
		"func-style":                       ["error", "expression"],
		"grouped-accessor-pairs":           ["error"],
		"max-depth":                        ["error", { max: 4 }],
		"init-declarations":                ["error"],
		"max-classes-per-file":             ["error", 1],
		"max-lines":                        ["error", { max: 500, skipBlankLines: true, skipComments: true }],
		"max-lines-per-function":           ["error", { max: 50, skipBlankLines: true, skipComments: true }],
		"max-nested-callbacks":             ["error", { max: 2 }],
		"max-params":                       ["error", { max: 10 }],
		"max-statements":                   ["error", { max: 20 }],
		"multiline-comment-style":          ["error", "starred-block"],
		"new-cap":                          ["error"],
		"no-alert":                         ["error"],
		"no-array-constructor":             ["error"],
		"no-bitwise":                       ["error", { int32Hint: true }],
		"no-caller":                        ["error"],
		"no-case-declarations":             ["error"],
		"no-console":                       ["warn"],
		"no-delete-var":                    ["error"],
		"no-else-return":                   ["error"],
		"no-empty":                         ["error"],
		"no-empty-function":                ["error"],
		"no-eq-null":                       ["error"],
		"no-eval":                          ["error"],
		"no-extend-native":                 ["error"],
		"no-extra-bind":                    ["error"],
		"no-extra-boolean-cast":            ["error"],
		"no-labels":                        ["error"],
		"no-extra-semi":                    ["error"],
		"no-floating-decimal":              ["error"],
		"no-global-assign":                 ["error"],
		"no-implicit-coercion":             ["error"],
		"no-implicit-globals":              ["error"],
		"no-implied-eval":                  ["error"],
		"no-invalid-this":                  ["error"],
		"no-iterator":                      ["error"],
		"no-lone-blocks":                   ["error"],
		"no-lonely-if":                     ["error"],
		"no-loop-func":                     ["error"],
		"no-mixed-operators":               ["error"],
		"no-multi-assign":                  ["error"],
		"no-multi-str":                     ["error"],
		"no-negated-condition":             ["error"],
		"no-nested-ternary":                ["error"],
		"no-new":                           ["error"],
		"no-new-object":                    ["error"],
		"no-new-func":                      ["error"],
		"no-new-wrappers":                  ["error"],
		"no-nonoctal-decimal-escape":       ["error"],
		"no-octal":                         ["error"],
		"no-octal-escape":                  ["error"],
		"no-param-reassign":                ["error"],
		"no-plusplus":                      ["error", { allowForLoopAfterthoughts: true }],
		"no-proto":                         ["error"],
		"no-regex-spaces":                  ["error"],
		"no-return-assign":                 ["error"],
		"no-script-url":                    ["error"],
		"no-sequences":                     ["error"],
		"no-shadow":                        ["error"],
		"no-shadow-restricted-names":       ["error"],
		"no-throw-literal":                 ["error"],
		"no-unneeded-ternary":              ["error"],
		"no-unused-expressions":            ["error"],
		"no-useless-call":                  ["error"],
		"no-useless-catch":                 ["error"],
		"no-useless-computed-key":          ["error"],
		"no-useless-concat":                ["error"],
		"no-useless-constructor":           ["error"],
		"no-useless-escape":                ["error"],
		"no-useless-rename":                ["error"],
		"no-useless-return":                ["error"],
		"no-void":                          ["error"],
		"no-warning-comments":              ["warn", { terms: ["todo", "fixme"] }],
		"no-with":                          ["error"],
		"object-shorthand":                 ["error"],
		"one-var":                          ["error", "never"],
		"prefer-arrow-callback":            ["error"],
		"prefer-const":                     ["error"],
		"prefer-exponentiation-operator":   ["error"],
		"prefer-named-capture-group":       ["warn"],
		"prefer-numeric-literals":          ["error"],
		"prefer-object-has-own":            ["error"],
		"prefer-object-spread":             ["error"],
		"prefer-promise-reject-errors":     ["error", { allowEmptyReject: true }],
		"prefer-regex-literals":            ["error"],
		"prefer-rest-params":               ["error"],
		"prefer-spread":                    ["error"],
		"prefer-template":                  ["error"],
		"quote-props":                      ["error", "consistent-as-needed"],
		"radix":                            ["error"],
		"require-unicode-regexp":           ["error"],
		"strict":                           ["error"],
		"symbol-description":               ["error"],
		"yoda":                             ["error", "never"],
		"arrow-parens":                     ["error"],
		"arrow-spacing":                    ["error"],
		"block-spacing":                    ["error"],
		"brace-style":                      ["error", "1tbs", { allowSingleLine: true }],
		"comma-dangle":                     ["error", "only-multiline"],
		"comma-spacing":                    ["error"],
		"comma-style":                      ["error", "last"],
		"computed-property-spacing":        ["error"],
		"dot-location":                     ["error", "property"],
		"eol-last":                         ["error"],
		"func-call-spacing":                ["error"],
		"function-call-argument-newline":   ["error", "consistent"],
		"generator-star-spacing":           ["error", { before: false, after: true }],
		"implicit-arrow-linebreak":         ["error", "beside"],
		"key-spacing":                      ["error", { align: "value" }],
		"lines-between-class-members":      ["error", "always"],
		"max-len":                          ["error", { code: 140, tabWidth: 4, ignoreComments: true }],
		"max-statements-per-line":          ["error", { max: 1 }],
		"new-parens":                       ["error"],
		"no-extra-parens":                  ["off"],
		"no-mixed-spaces-and-tabs":         ["error", "smart-tabs"],
		"no-multiple-empty-lines":          ["error", { max: 1, maxBOF: 0, maxEOF: 0 }],
		"no-trailing-spaces":               ["error"],
		"no-whitespace-before-property":    ["error"],
		"nonblock-statement-body-position": ["error", "below"],
		"object-curly-spacing":             ["error", "always"],
		"operator-linebreak":               ["error", "before"],
		"padded-blocks":                    ["error", { blocks: "never", classes: "always", switches: "never" }],
		"rest-spread-spacing":              ["error", "never"],
		"semi-spacing":                     ["error", { before: false, after: true }],
		"space-before-function-paren":      ["error", { anonymous: "never", named: "never", asyncArrow: "always" }],
		"space-in-parens":                  ["error", "never"],
		"space-infix-ops":                  ["error"],
		"switch-colon-spacing":             ["error", { after: true, before: false }],
		"template-curly-spacing":           ["error", "never"],
		"template-tag-spacing":             ["error", "never"],
		"wrap-iife":                        ["error", "outside"],
		"yield-star-spacing":               ["error", "after"],
		"no-multi-spaces":                  ["off"],
		"no-constant-condition":            ["error", { checkLoops: false }],
		

		"unicorn/better-regex":                            ["warn"],
		"unicorn/catch-error-name":                        ["error", { name: "err" }],
		"unicorn/consistent-function-scoping":             ["error"],
		"unicorn/custom-error-definition":                 ["error"],
		"unicorn/error-message":                           ["error"],
		"unicorn/escape-case":                             ["error"],
		"unicorn/expiring-todo-comments":                  ["error", { terms: ["todo", "fixme"] }],
		"unicorn/explicit-length-check":                   ["error"],
		"unicorn/new-for-builtins":                        ["error"],
		"unicorn/no-abusive-eslint-disable":               ["error"],
		"unicorn/no-array-callback-reference":             ["error"],
		"unicorn/no-array-for-each":                       ["error"],
		"unicorn/no-array-method-this-argument":           ["error"],
		"unicorn/no-array-push-push":                      ["error"],
		"unicorn/no-array-reduce":                         ["error"],
		"unicorn/no-await-expression-member":              ["error"],
		"unicorn/no-console-spaces":                       ["error"],
		"unicorn/no-document-cookie":                      ["error"],
		"unicorn/no-empty-file":                           ["error"],
		"unicorn/no-for-loop":                             ["error"],
		"unicorn/no-hex-escape":                           ["error"],
		"unicorn/no-instanceof-array":                     ["error"],
		"unicorn/no-invalid-remove-event-listener":        ["error"],
		"unicorn/no-lonely-if":                            ["error"],
		"unicorn/no-new-buffer":                           ["error"],
		"unicorn/no-object-as-default-parameter":          ["error"],
		"unicorn/no-static-only-class":                    ["error"],
		"unicorn/no-thenable":                             ["error"],
		"unicorn/no-this-assignment":                      ["error"],
		"unicorn/no-unreadable-array-destructuring":       ["error"],
		"unicorn/no-unsafe-regex":                         ["error"],
		"unicorn/no-useless-fallback-in-spread":           ["error"],
		"unicorn/no-useless-length-check":                 ["error"],
		"unicorn/no-useless-promise-resolve-reject":       ["error"],
		"unicorn/no-useless-spread":                       ["error"],
		"unicorn/number-literal-case":                     ["error"],
		"unicorn/numeric-separators-style":                ["error"],
		"unicorn/prefer-add-event-listener":               ["error"],
		"unicorn/prefer-array-find":                       ["error"],
		"unicorn/prefer-array-flat":                       ["error"],
		"unicorn/prefer-array-flat-map":                   ["error"],
		"unicorn/prefer-array-index-of":                   ["error"],
		"unicorn/prefer-array-some":                       ["error"],
		"unicorn/prefer-at":                               ["error"],
		"unicorn/prefer-code-point":                       ["error"],
		"unicorn/prefer-date-now":                         ["error"],
		"unicorn/prefer-default-parameters":               ["error"],
		"unicorn/prefer-dom-node-append":                  ["error"],
		"unicorn/prefer-dom-node-dataset":                 ["error"],
		"unicorn/prefer-dom-node-remove":                  ["error"],
		"unicorn/prefer-dom-node-text-content":            ["error"],
		"unicorn/prefer-event-target":                     ["error"],
		"unicorn/prefer-includes":                         ["error"],
		"unicorn/prefer-json-parse-buffer":                ["error"],
		"unicorn/prefer-keyboard-event-key":               ["error"],
		"unicorn/prefer-logical-operator-over-ternary":    ["error"],
		"unicorn/prefer-math-trunc":                       ["error"],
		"unicorn/prefer-modern-dom-apis":                  ["error"],
		"unicorn/prefer-modern-math-apis":                 ["error"],
		"unicorn/prefer-native-coercion-functions":        ["error"],
		"unicorn/prefer-negative-index":                   ["error"],
		"unicorn/prefer-node-protocol":                    ["error"],
		"unicorn/prefer-number-properties":                ["error"],
		"unicorn/prefer-object-from-entries":              ["error"],
		"unicorn/prefer-optional-catch-binding":           ["error"],
		"unicorn/prefer-prototype-methods":                ["error"],
		"unicorn/prefer-query-selector":                   ["error"],
		"unicorn/prefer-reflect-apply":                    ["error"],
		"unicorn/prefer-regexp-test":                      ["error"],
		"unicorn/prefer-set-has":                          ["error"],
		"unicorn/prefer-spread":                           ["error"],
		"unicorn/prefer-string-replace-all":               ["error"],
		"unicorn/prefer-string-slice":                     ["error"],
		"unicorn/prefer-string-starts-ends-with":          ["error"],
		"unicorn/prefer-string-trim-start-end":            ["error"],
		"unicorn/prefer-switch":                           ["error"],
		"unicorn/prefer-type-error":                       ["error"],
		"unicorn/relative-url-style":                      ["error", "always"],
		"unicorn/require-array-join-separator":            ["error"],
		"unicorn/require-number-to-fixed-digits-argument": ["error"],
		"unicorn/require-post-message-target-origin":      ["error"],
		"unicorn/text-encoding-identifier-case":           ["error"],
		"unicorn/throw-new-error":                         ["error"],

		"import/named":                      ["error"],
		"import/default":                    ["error"],
		"import/namespace":                  ["error"],
		"import/no-absolute-path":           ["error"],
		"import/no-dynamic-require":         ["error"],
		"import/no-self-import":             ["error"],
		"import/no-cycle":                   ["error"],
		"import/no-useless-path-segments":   ["error"],
		"import/no-relative-parent-imports": ["error"],
		"import/no-relative-packages":       ["error"],
		"import/export":                     ["error"],
		"import/no-named-as-default":        ["error"],
		"import/no-named-as-default-member": ["error"],
		"import/no-deprecated":              ["error"],
		"import/no-extraneous-dependencies": ["error", { devDependencies: ["**/tests/**/*.js", "tests/**/*.js", "tests/*.js"] }],
		"import/no-mutable-exports":         ["error"],
		"import/no-unused-modules":          ["error"],
		"import/first":                      ["error"],
		"import/no-duplicates":              ["error"],
		"import/order":                      ["error", { "newlines-between": "always" }],
		"import/newline-after-import":       ["error"],
		"import/max-dependencies":           ["error", { max: 15 }],
		"import/dynamic-import-chunkname":   ["error"],
	},
}
